import datetime
#this will return current date time
print(datetime.datetime.now())
print(datetime.datetime(2022,2,12))

x=(datetime.datetime.now())
m1=x.strftime(("%y"))
m2=x.strftime(("%Y"))
m3=x.strftime(("%b"))
m4=x.strftime(("%B"))
m5=x.strftime(("%M"))
m6=x.strftime(("%Y"))
m7=x.strftime(("%S"))
m8=x.strftime(("%H"))
m9=x.strftime(("%I"))
print(m1)
print(m2)
print(m3)
print(m4)
print(m5)
print(m6)
print(m7)
print(m8)
print(m9)
print(m8,":",m5,":",m7)